USE DATABASE FEATURESTORE_DB;
USE SCHEMA FEATURESTORE_SCHEMA;
USE ROLE ACCOUNTADMIN;

CREATE or REPLACE NOTIFICATION INTEGRATION EMAIL_INT
  TYPE=EMAIL
  ENABLED=TRUE
  ALLOWED_RECIPIENTS=('raymondcanchola@gmail.com');

GRANT OWNERSHIP ON INTEGRATION EMAIL_INT TO ROLE FEATURESTORE_ROLE;
GRANT USAGE ON INTEGRATION EMAIL_INT TO ROLE FEATURESTORE_ROLE;
