USE ROLE ACCOUNTADMIN;
-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE FEATURESTORE_ROLE;
GRANT ROLE FEATURESTORE_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE FEATURESTORE_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE FEATURESTORE_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE FEATURESTORE_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE FEATURESTORE_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE FEATURESTORE_ROLE;

-- Databases
CREATE OR REPLACE DATABASE FEATURESTORE_DB;
GRANT OWNERSHIP ON DATABASE FEATURESTORE_DB TO ROLE FEATURESTORE_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE FEATURESTORE_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE FEATURESTORE_WH TO ROLE FEATURESTORE_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE FEATURESTORE_ROLE;
USE WAREHOUSE FEATURESTORE_WH;
USE DATABASE FEATURESTORE_DB;

-- External Frostbyte objects
CREATE OR REPLACE SCHEMA FEATURESTORE_SCHEMA;

USE SCHEMA FEATURESTORE_SCHEMA;
CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER=1
    Trim_Space=TRUE
;
