name: Deploy Snowpark Apps

on:
  pull_request:
    branches:
      - master
      - dev
      - test
      - release
    types:
      - closed
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select the target branch for deployment'
        required: true
        default: 'dev'
        options:
          - dev
          - test
          - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      MANUAL_GITHUB_WORKSPACE: "/home/runner/work/repo_3_env/blob/dev"  # Set the correct path to your repository

    steps:
      - name: Set Environment Variables
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "TARGET_BRANCH=${{ inputs.target_branch }}" >> $GITHUB_ENV
          else
            echo "TARGET_BRANCH=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          fi
          echo "SNOWSQL_ACCOUNT=${{ secrets[format('SNOWSQL_ACCOUNT_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_USER=${{ secrets[format('SNOWSQL_USER_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_PWD=${{ secrets[format('SNOWSQL_PWD_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_ROLE=${{ secrets[format('SNOWSQL_ROLE_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_WAREHOUSE=${{ secrets[format('SNOWSQL_WAREHOUSE_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_DATABASE=${{ secrets[format('SNOWSQL_DATABASE_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV
          echo "SNOWSQL_SCHEMA=${{ secrets[format('SNOWSQL_SCHEMA_{0}', inputs.target_branch)] }}" >> $GITHUB_ENV

      - name: Check Target Branch
        run: |
          if [ "$TARGET_BRANCH" == "dev" ] || [ "$TARGET_BRANCH" == "test" ] || [ "$TARGET_BRANCH" == "release" ]; then
            echo "Deploying to $TARGET_BRANCH branch"
          else
            echo "Invalid target branch: $TARGET_BRANCH"
            exit 1
          fi

      # Add your deployment steps here based on the target branch and secrets
      - name: Deploy Snowpark apps
        run: python $MANUAL_GITHUB_WORKSPACE/command_center_deploy.py --root_directory=$MANUAL_GITHUB_WORKSPACE --files_list="${{ steps.filenames.outputs.all }}"
