name: Deploy Snowpark Apps

on:
  pull_request:
    branches:
      - dev
      - test
      - release
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, test, release]

    steps:
      - name: Set Environment Variables
        run: |
          echo "SNOWSQL_ACCOUNT=${{ fromJSON(secrets[format('SNOWSQL_ACCOUNT_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_USER=${{ fromJSON(secrets[format('SNOWSQL_USER_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_PWD=${{ fromJSON(secrets[format('SNOWSQL_PWD_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_ROLE=${{ fromJSON(secrets[format('SNOWSQL_ROLE_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_WAREHOUSE=${{ fromJSON(secrets[format('SNOWSQL_WAREHOUSE_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_DATABASE=${{ fromJSON(secrets[format('SNOWSQL_DATABASE_{0}', matrix.environment)]) }}" >> $GITHUB_ENV
          echo "SNOWSQL_SCHEMA=${{ fromJSON(secrets[format('SNOWSQL_SCHEMA_{0}', matrix.environment)]) }}" >> $GITHUB_ENV

      - name: Configure snowcli
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections.main]" > config
          echo "accountname = $SNOWSQL_ACCOUNT " >> config
          echo "username = $SNOWSQL_USER " >> config
          echo "password = $SNOWSQL_PWD " >> config
          echo "rolename = $SNOWSQL_ROLE " >> config
          echo "warehousename = $SNOWSQL_WAREHOUSE " >> config
          echo "dbname = $SNOWSQL_DATABASE " >> config
          echo "schemaname = $SNOWSQL_SCHEMA " >> config

      - name: Deploy Snowpark apps
        run: python command_center_deploy.py --root_directory=$GITHUB_WORKSPACE --files_list="${{ steps.filenames.outputs.all }}"
