name: Deploy Snowpark Apps

on:
  pull_request:
    branches:
      - [dev, test, release]
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, test, release]

    env:
      SNOWSQL_ACCOUNT: ${{ secrets["SNOWSQL_ACCOUNT_" + matrix.environment] }}
      SNOWSQL_USER: ${{ secrets["SNOWSQL_USER_" + matrix.environment] }}
      SNOWSQL_PWD: ${{ secrets["SNOWSQL_PWD_" + matrix.environment] }}
      SNOWSQL_ROLE: ${{ secrets["SNOWSQL_ROLE_" + matrix.environment] }}
      SNOWSQL_WAREHOUSE: ${{ secrets["SNOWSQL_WAREHOUSE_" + matrix.environment] }}
      SNOWSQL_DATABASE: ${{ secrets["SNOWSQL_DATABASE_" + matrix.environment] }}
      SNOWSQL_SCHEMA: ${{ secrets["SNOWSQL_SCHEMA_" + matrix.environment] }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: pip install -r requirements.txt

      - name: Configure snowcli
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections.main]" > config
          echo "accountname = $SNOWSQL_ACCOUNT " >> config
          echo "username = $SNOWSQL_USER " >> config
          echo "password = $SNOWSQL_PWD " >> config
          echo "rolename = $SNOWSQL_ROLE " >> config
          echo "warehousename = $SNOWSQL_WAREHOUSE " >> config
          echo "dbname = $SNOWSQL_DATABASE " >> config
          echo "schemaname = $SNOWSQL_SCHEMA " >> config

      - name: Deploy Snowpark apps
        run: python command_center_deploy.py --root_directory=$GITHUB_WORKSPACE --files_list="${{ steps.filenames.outputs.all }}"
