name: Deploy Snowpark Apps

on:
  pull_request:
    branches:
      - dev
      - test
      - release
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, test, release]

    env:
      SNOWSQL_ACCOUNT: ${{ fromJSON(secrets["SNOWSQL_ACCOUNT_" + matrix.environment]) }}
      SNOWSQL_USER: ${{ fromJSON(secrets["SNOWSQL_USER_" + matrix.environment]) }}
      SNOWSQL_PWD: ${{ fromJSON(secrets["SNOWSQL_PWD_" + matrix.environment]) }}
      SNOWSQL_ROLE: ${{ fromJSON(secrets["SNOWSQL_ROLE_" + matrix.environment]) }}
      SNOWSQL_WAREHOUSE: ${{ fromJSON(secrets["SNOWSQL_WAREHOUSE_" + matrix.environment]) }}
      SNOWSQL_DATABASE: ${{ fromJSON(secrets["SNOWSQL_DATABASE_" + matrix.environment]) }}
      SNOWSQL_SCHEMA: ${{ fromJSON(secrets["SNOWSQL_SCHEMA_" + matrix.environment]) }}

    steps:
      - name: Configure snowcli
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections.main]" > config
          echo "accountname = $SNOWSQL_ACCOUNT " >> config
          echo "username = $SNOWSQL_USER " >> config
          echo "password = $SNOWSQL_PWD " >> config
          echo "rolename = $SNOWSQL_ROLE " >> config
          echo "warehousename = $SNOWSQL_WAREHOUSE " >> config
          echo "dbname = $SNOWSQL_DATABASE " >> config
          echo "schemaname = $SNOWSQL_SCHEMA " >> config

      - name: Deploy Snowpark apps
        run: python command_center_deploy.py --root_directory=$GITHUB_WORKSPACE --files_list="${{ steps.filenames.outputs.all }}"
